name: my_archery
description: MyArchery Admin Mobile App

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.5+28

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.1
  get_storage: 2.0.3
#  alice: ^0.2.5
  pretty_dio_logger:
  dio: ^4.0.0
  json_serializable: ^6.1.5
  json_annotation: ^4.4.0
  equatable: ^2.0.2
  google_fonts: ^2.1.0
  flutter_svg: ^1.0.3
  intl: ^0.17.0

  flutter_launcher_icons: ^0.9.2
  url_launcher: ^6.0.10
  loading_indicator: ^3.0.3
  flutter_fadein: ^2.0.0
  mobile_scanner: ^2.0.0
  flutter_dotenv: ^5.0.2
  webview_flutter: ^3.0.4
  clippy_flutter: ^2.0.0-nullsafety.1

  printing:

#  carousel_slider: ^4.0.0
  scroll_to_index: ^3.0.1
  syncfusion_flutter_pdfviewer: ^20.1.52-beta



dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_gen_runner:

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/img/ic_launcher.png"

flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/icons/
    - .env.development
    - .env.production
