name: myarchery_archer
description: Archer Mobile App

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.2+17

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: 4.1.4
  get_storage: 2.0.3
  alice: ^0.2.5
  pretty_dio_logger:
  dio: ^4.0.0
  json_serializable: ^4.1.4
  json_annotation: ^4.0.0
  equatable: ^2.0.2
  google_fonts: ^2.1.0
  flutter_svg: ^0.22.0
  intl: ^0.17.0
  flutter_dotenv: ^5.0.2

  device_info_plus: ^3.2.2
  package_info_plus: ^1.4.0

  flutter_launcher_icons: ^0.9.2
  url_launcher: ^6.0.10
  loading_indicator: ^2.0.0
  flutter_fadein: ^2.0.0
  flutter_keyboard_visibility: ^5.0.3
  clippy_flutter: ^2.0.0-nullsafety.1
  visibility_detector: ^0.2.2
  oktoast: ^3.1.5

  #animation
  flutter_staggered_animations: ^1.0.0
  shimmer: ^2.0.0

  pin_code_fields: ^7.3.0

  #image processor
  image_picker: ^0.8.4+4
  image_cropper: ^1.5.1
  flutter_image_compress: ^1.1.0

  flutter_speed_dial: ^5.0.0+1
  flutter_countdown_timer: ^4.1.0
  simple_shadow: ^0.3.0
  fbroadcast_nullsafety: ^2.0.2

  webview_flutter: ^3.0.0

  photo_view: ^0.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_gen_runner:

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/img/ic_launcher.png"

flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/icons/
    - .env.development
    - .env.production