name: myarcher_enterprise
description: MyArchery Enterprise

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  alice: ^0.2.5
  get: ^4.6.1
  get_storage: 2.0.3
  pretty_dio_logger:
  dio: ^4.0.0
  json_serializable: ^6.1.5
  json_annotation: ^4.4.0
  equatable: ^2.0.2
  google_fonts: ^2.1.0
  flutter_svg: ^1.0.0
  intl: ^0.17.0

  flutter_launcher_icons: ^0.9.2
  url_launcher: ^6.1.2
  loading_indicator: ^3.0.3

  simple_shadow: ^0.3.0
  shimmer: ^2.0.0
  flutter_html: ^3.0.0-alpha.2
  photo_view: ^0.13.0

  flutter_image_compress: ^1.1.0
  image_cropper: ^2.0.3
  image_picker: ^0.8.5

  google_maps_flutter: ^2.1.10
  geolocator: ^8.0.3
  geocoder: ^0.2.1
  google_place: ^0.4.7

  #push notif
  firebase_messaging: ^11.4.1
  firebase_core: ^1.20.0
  flutter_local_notifications: ^9.5.3+1

  flutter_dotenv: ^5.0.2
  device_info_plus: ^3.2.2
  package_info_plus: ^1.4.0
  cupertino_icons: ^1.0.2

  flutter_fadein: ^2.0.0
  email_validator: ^2.0.1
  cached_network_image: ^3.2.1

  oktoast: ^3.1.5
  pin_code_fields: ^7.3.0

  syncfusion_flutter_datepicker: ^20.2.40
  flutter_slidable: ^2.0.0
  event_bus: ^2.0.0

#  better_player:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_gen_runner:
  build_runner:

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - .env.development
    - .env.production

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/ic_launcher.png"